services:
  web-api:
    build: ./src/.
    container_name: notification-service
    restart: always
    environment:
      - APP_NAME=Notification_Service
    ports:
      - 80:5000
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: notification_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    ports:
      - 27017:27017
    restart: always
    command: ["mongod"]