services:
  web-api:
    build: ./src/.
    container_name: notification-service
    restart: always
    environment:
      - APP_NAME=Notification_Service
    ports:
      - 8080:5000

  nginx:
    build: ./nginx/.
    container_name: nginx
    restart: always