name: CD Pipeline

# Trigger only, when build workflow succeeds.
on:
  workflow_run:
    workflows: ["CI pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Run the latest service build.
        if: ${{ hashFiles('docker-compose.yml') != '' }}
        run: docker run -d notification-service:latest
