name: CD Pipeline

# Trigger only, when build workflow succeeds.
on:
  workflow_run:
    workflows: ["CI pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - name: Run the latest service build.
        if: ${{ hashFiles('docker-compose.yml') != '' }}
        uses: adambirds/docker-compose-action@v1.3.0

      - name: Run Docker Compose
        if: ${{ hashFiles('docker-compose.yml') != '' }}
        run: docker-compose up -d

