name: CI pipeline

# Trigger deployment only when pushed to the main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker Images
    runs-on: self-hosted
    steps:
      - name: Checkout Current Commit.
        uses: actions/checkout@v3

      - name: Setup Docker
        if: ${{ hashFiles('docker-compose.yml') != '' }}
        uses: docker/setup-buildx-action@v2

      - name: Check and build Docker Images.
        if: ${{ hashFiles('docker-compose.yml') != '' }}
        run: docker build ./src/ -t notification-service:latest

        